version: "3.8"

services: 
    ghostpp:
        container_name: bot1
        image: fatorin/ghostpp:1.2
        ports: 
            - "6113:6113"
            - "6114:6114"
        volumes: 
            - ./config:app/config
            - ./maps:app/maps
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: 512M
                reservations:
                    cpus: "0.1"
                    memory: 128M